[workspace]
authors = ["yufei4hua <michael4hua@gmail.com>"]
channels = ["pytorch", "nvidia", "conda-forge"]
name = "franesis"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
pip = ">=25.1.1,<26"
numpy = "==1.26.4"
matplotlib = "*"
toml = ">=0.10.2"
openblas = ">=0.3.30,<0.4"
ruff = "*"
pyopengl = "*"
pinocchio = "*"

[pypi-dependencies]
PyOpenGL_accelerate = "*"
genesis-world = "*"
torch = "*"

[pypi-options.dependency-overrides]
pillow = ">=9.2.0"
